<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net5.0-windows7.0</TargetFramework>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <NeutralLanguage>en</NeutralLanguage>
    <Version>1.1.0</Version>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Common.Logging" Version="3.4.1" />
    <PackageReference Include="ParallelExtensionsExtras.NetFxStandard" Version="1.4.0" />
  </ItemGroup>

</Project>
